### ISSUE TITLE
SEA- Session at collaborator summit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/single-executable#32]
The collaborator summit is comming up later this month - https://openjsf.org/blog/2022/09/01/openjs-collaborator-summit-join-us-in-dublin-virtual-october-1-2%EF%BF%BC/

Not sure who will be there from this team, but if there are enough people sumitting a proposal for a session here - https://github.com/openjs-foundation/summit might make sense.

**Comment by jviotti** [comment]
Interesting. I can probably make it to Dublin and help host a session around SEA discussions. I'll submit a proposal

**Comment by jviotti** [comment]
Done! https://github.com/openjs-foundation/summit/issues/334 cc @RaisinTen @robertgzr @dsanders11 in case you are interested on traveling to Dublin

**Comment by mhdawson** [comment]
@jviotti thanks for submitting the proposal, looking forward to it.

**Comment by RaisinTen** [comment]
I'd be excited to participate in the session but I won't be able to attend in-person, so I can probably help out virtually! :)

**Comment by ovflowd** [comment]
Excited to participate, will be attending in-person :)

**Comment by RaisinTen** [comment]
Ping @nodejs/single-executable in case anyone else is also interested in participating. :)

We were thinking about doing something like a regular single-executable team meeting with more focus on the roadmap. What does everybody think? Better suggestions and ideas?

**Comment by arcanis** [comment]
Hm, I have long-planned vacations on this week-end, and I'd have liked to attend the roadmap meeting 🙁

**Comment by jviotti** [comment]
We'll make sure to record it @arcanis !

**Comment by jviotti** [comment]
Thanks for hosting us @mhdawson and thanks everybody for attending (in-person and remotely!) Here are my notes from our conversation.

***

- There is general agreement that we want to try as hard as possible to make SEAs truly "single executable" without additional resources
- There is agreement that we don't want Node.js to support a single specific blessed VFS. Instead, Node.js should aim to provide the necessary hooks for supporting arbitrary VFS implementations
- Teaching Node.js how to transparently work with a VFS on `fs`, `require`, `import` and `child_process` is non-trivial. We agreed that we do not want implementations to continue monkey-patching these modules and that monkey-patching will not work with ESM at all
- Exposing hooking capabilities is a complex problem. While we agree that a VFS is essential for supporting dynamic requires, read operations, etc we believe that there is a significant number of Node.js CLIs that might not need this
- Therefore, we can explore delivering an MVP *without* a VFS while we continue thinking about how we'll do VFS properly
- This MVP would assume that apps are bundled into a single JavaScript file before injection
- Node.js core would take a small patch to detect a single file embedded as a section and jump to it if found
- In the interest of making Node.js binaries smaller without operating custom Node.js builds, we will move the ICU data into a new section, so it can be replaced by the ICU "small" data (or removed?) if needed post-compilation rather than at build-time
- We expect that distributing Node.js injected binaries to user computers will come with challenges we want to solve in advance. For example, Windows PE binaries including plain JavaScript tend to be flagged by AntiViruses as trojans. We will start maintaining a list of these challenges and then try to figure out how to incrementally solve them.

**Action Items**

- [ ] @RaisinTen - Send patch to https://github.com/nodejs/node to detect and jump to a section containing a single JavaScript file if found  
- [ ] @jviotti Collect a list of potential problems we would face when distributing Node.js injected binaries to user computers across operating systems
- [ ] @dsanders11 @robertgzr @RaisinTen Split Node.js ICU data into its own section (so we can fiddle with it with Postject)
- [ ] @No9 Connect us with IBM AIX folks to understand the need for SEAs on AIX (and potential XCOFF help?)
- [ ] @jviotti @RaisinTen @dsanders11 @robertgzr Start working on a proper "SEA" CLI MVP that can bundle and inject simple Node.js applications

**Other ideas (mainly for the record)**

- We could explore splitting different Node.js modules (like `fs`) into separate sections to strip them out for applications that do not need them
- We could explore a different mechanism for loading native add-ons in order to embed them into the executable itself. For example, marking the corresponding sections as readable + executable and doing a long jump to the instructions corresponding to the add-ons instead of using `dlopen`, etc

Do let me know if I missed anything else!

**Comment by RaisinTen** [comment]
@jviotti thanks for sharing the notes, it might be worth PR'ing this into https://github.com/nodejs/single-executable/tree/main/meetings

**Comment by jviotti** [comment]
Makes sense! See https://github.com/nodejs/single-executable/pull/50
