### ISSUE TITLE
Preserving the code signature (Windows)

### ISSUE THREAD

**Issue by AndrewMD5** [nodejs/single-executable#72]
Hi,

I wasn't sure if this was on the radar of the team, but it is actually possible, at least on Windows to inject custom data into an existing signed binary without the code signature becoming invalid. You can see an example [here](https://github.com/RainwayApp/MetaPod) for 32-bit and 64-bit applications.

I only bring this up because I noticed SmartScreen flags the executable as being unverified after injecting the blob.

**Comment by RaisinTen** [comment]
Where does MetaPod inject the metadata into the PE file? Does it create a new resource?

> I only bring this up because I noticed SmartScreen flags the executable as being unverified after injecting the blob.

Does it still flag the executable once it is signed after the injection?

---

I think it's a good sign that SmartScreen flags the executable after the injection because developers might not want their end users to be able to change the application code that has been injected into the app binary without invalidating the signature.

**Comment by AndrewMD5** [comment]
> Where does MetaPod inject the metadata into the PE file? Does it create a new resource?


It adds an adds a superfluous certificate to a portable executable; the appended data is "unverified" and does affect the PE's digital signature. The certificate has 'ExtraExtensions' which contains payload data that can later be looked up at runtime to pull any custom data set on it out.

**Comment by RaisinTen** [comment]
> On Windows at least this is easily bypassed using resource hooks to redirect resource load calls so you can modify resource contents without modifying the executable itself.

Do you know of any other way of injecting data into a PE file so that it is also protected by the code signature, i.e., also guard against resource hooks, etc.?

> Since EV certificates are expensive and automation is annoying, for QOL having preserving the NodeJS signature would allow the applications to run without user intervention.

In order to do that, we would have to put the payload into the `ExtraExtensions` property of a new X509 certificate, which we are gonna append into the pre-existing list of digital signatures in the PE file, right? (I'm not a Go expert, just trying to verify that I understood your code correctly) Also, how will the executable load the injected data - does it have to parse the entire binary for it or is it loaded in memory when the process starts? Is there any limitation on the size of the data that could be injected here?

If we go with this approach, do you have any thoughts on how else we can prevent modifications of the injected code?

Also, cc @bmeck because IIUC protecting the injected data using the code signature is a requirement for https://github.com/nodejs/security-wg/issues/879. Maybe you or the Microsoft folks who were involved in the discussion have any thoughts on this?

cc @nodejs/single-executable

**Comment by bmeck** [comment]
@RaisinTen the MS talks we have had would sign it via a separate cert that lives beside the executable as a separate file for Windows to use. From my end the only part that we would need to be sure is valid and cannot be patched is a bundled flag to force that integration to always be active.

**Comment by RaisinTen** [comment]
> From my end the only part that we would need to be sure is valid and cannot be patched is a bundled flag to force that integration to always be active.

@bmeck if the bundled flag stays on a new resource on the Node.js binary, to @AndrewMD5's point, that too could actually still be patched:

> On Windows at least this is easily bypassed using resource hooks to redirect resource load calls so you can modify resource contents without modifying the executable itself.

**Comment by AndrewMD5** [comment]
Sorry for the late reply, been on a crunch. 

>Do you know of any other way of injecting data into a PE file so that it is also protected by the code signature, i.e., also guard against resource hooks, etc.?

It's an arms race. There isn't really a way to prevent anything on Windows (nor is it really worth it). The executable should just be stored in a place that isn't writeable without administrative privileges if modifications are a concern. 

> In order to do that, we would have to put the payload into the ExtraExtensions property of a new X509 certificate, which we are gonna append into the pre-existing list of digital signatures in the PE file, right?

Correct.

> Also, how will the executable load the injected data - does it have to parse the entire binary for it or is it loaded in memory when the process starts? Is there any limitation on the size of the data that could be injected here?

At the process  opens itself with a read handle and jumps to where certs are stored and parses the value from the extensions. 


All that being said, after giving it some more thought, even if you did this approach I would be less concerned with potential modifications to injected code and more so potential malicious apps being distributed which get essentially a free  valid EV certificate (nodes) to hide their malware in. It's pretty trivial to self-elevate a process to administrator, users will be more likely to trust the Node organization name when it pops up on their desktop.

**Comment by bmeck** [comment]
> if the bundled flag stays on a new resource on the Node.js binary, to @AndrewMD5's point, that too could actually still be patched:

I'm neutral to how to fix this, but agree we cannot move forwards with it as a security measure util some kind of solution is viable; alternative could require shipping a custom build of the node executable with the flag statically built but that has major distribution issues.

**Comment by RaisinTen** [comment]
> potential malicious apps being distributed which get essentially a free valid EV certificate (nodes) to hide their malware in

> My suggestion is a good idea if you want to inject non-executable data, but not so much since the goal is to inject arbitrary code that will be ran.

I fully agree with your point. Since it can potentially make it easier to create and distribute malicious apps, we probably shouldn't be doing this, so I'll close this. But thanks for bringing this up!
